import type { Language } from "@/lib/i18n";
import { BRANDS, type Department } from "@/lib/brands";
import type { ReplyButton } from "./types";

/**
 * =============================================================================
 *  WhatsApp channel copy
 * =============================================================================
 *
 *  Everything the WhatsApp bot says that is *not* generated by the model: the
 *  welcome menu, confirmations, escalation notices and the quick-action chips.
 *
 *  Kept out of `lib/i18n.ts` on purpose — that dictionary serves the web UI,
 *  where labels sit on buttons in a rendered page. These strings are chat
 *  messages: they need emoji, line breaks and a warmer register, and they are
 *  only ever read inside WhatsApp.
 * =============================================================================
 */

type Localised = Record<Language, string>;

export const DEPARTMENT_BUTTON_PREFIX = "dept:";
export const ACTION_BUTTON_PREFIX = "act:";

function pick(copy: Localised, language: Language): string {
  return copy[language] ?? copy.en;
}

// ---------------------------------------------------------------- Welcome ---

const WELCOME: Localised = {
  en: "👋 *Welcome to BITSOL!*\n\nI'm your AI assistant. We run two businesses — please pick the one you need so I give you the right information.",
  ur: "👋 *بِٹسول میں خوش آمدید!*\n\nمیں آپ کا اے آئی اسسٹنٹ ہوں۔ ہمارے دو ادارے ہیں — براہِ کرم منتخب کریں تاکہ میں درست معلومات دے سکوں۔",
  ur_roman:
    "👋 *BITSOL mein khush aamdeed!*\n\nMain aap ka AI assistant hoon. Hamare do idaare hain — please select karein taake main sahi maloomat de sakun.",
  pa: "👋 *بِٹسول وچ جی آیاں نوں!*\n\nمیں تہاڈا اے آئی اسسٹنٹ آں۔ ساڈے دو ادارے نیں — چُݨ لوو تاں جو میں ٹھیک جاݨکاری دے سکاں۔",
};

const WELCOME_FOOTER: Localised = {
  en: "Reply *menu* any time to switch",
  ur: "تبدیلی کے لیے *menu* لکھیں",
  ur_roman: "Switch karne ke liye *menu* likhein",
  pa: "بدلݨ لئی *menu* لکھو",
};

export function welcomeMessage(language: Language): {
  text: string;
  buttons: ReplyButton[];
  footer: string;
} {
  return {
    text: pick(WELCOME, language),
    footer: pick(WELCOME_FOOTER, language),
    buttons: [
      {
        id: `${DEPARTMENT_BUTTON_PREFIX}MARKETING`,
        title: `${BRANDS.MARKETING.emoji} Marketing`,
      },
      {
        id: `${DEPARTMENT_BUTTON_PREFIX}INSTITUTE`,
        title: `${BRANDS.INSTITUTE.emoji} Institute`,
      },
    ],
  };
}

// --------------------------------------------------- Department greetings ---

const MARKETING_GREETING: Localised = {
  en: "🏢 *BITSOL Marketing*\n\nWe build AI chatbots, WhatsApp automation, websites, apps and complete brand systems.\n\nAsk me anything — pricing, process, past work — or tap below to get a proposal.",
  ur: "🏢 *بِٹسول مارکیٹنگ*\n\nہم اے آئی چیٹ بوٹس، واٹس ایپ آٹومیشن، ویب سائٹس، ایپس اور مکمل برانڈ سسٹم بناتے ہیں۔\n\nقیمت، طریقۂ کار یا پچھلے کام — کچھ بھی پوچھیں، یا نیچے سے تجویز حاصل کریں۔",
  ur_roman:
    "🏢 *BITSOL Marketing*\n\nHum AI chatbots, WhatsApp automation, websites, apps aur complete brand systems banate hain.\n\nPricing, process ya pichla kaam — kuch bhi poochein, ya neeche se proposal lein.",
  pa: "🏢 *بِٹسول مارکیٹنگ*\n\nاسی اے آئی چیٹ بوٹ، واٹس ایپ آٹومیشن، ویب سائٹاں، ایپاں تے پورے برانڈ سسٹم بݨاندے آں۔\n\nریٹ، طریقہ یا پچھلا کم — کجھ وی پُچھو، یا تھلے توں تجویز لوو۔",
};

const INSTITUTE_GREETING: Localised = {
  en: "🎓 *BITSOL Institute of Digital Media & AI*\n\nProject-based courses in digital marketing, AI, design, video, development and freelancing — with a certificate and career support.\n\nAsk about any course, fee or batch, or tap below to apply.",
  ur: "🎓 *بِٹسول انسٹی ٹیوٹ آف ڈیجیٹل میڈیا اینڈ اے آئی*\n\nڈیجیٹل مارکیٹنگ، اے آئی، ڈیزائن، ویڈیو، ڈویلپمنٹ اور فری لانسنگ کے پروجیکٹ بیسڈ کورسز — سرٹیفکیٹ اور کیریئر سپورٹ کے ساتھ۔\n\nکسی بھی کورس، فیس یا بیچ کے بارے میں پوچھیں، یا نیچے سے درخواست دیں۔",
  ur_roman:
    "🎓 *BITSOL Institute of Digital Media & AI*\n\nDigital marketing, AI, design, video, development aur freelancing ke project-based courses — certificate aur career support ke saath.\n\nKisi bhi course, fee ya batch ke baare mein poochein, ya neeche se apply karein.",
  pa: "🎓 *بِٹسول انسٹی ٹیوٹ آف ڈیجیٹل میڈیا اینڈ اے آئی*\n\nڈیجیٹل مارکیٹنگ، اے آئی، ڈیزائن، ویڈیو، ڈویلپمنٹ تے فری لانسنگ دے پروجیکٹ بیسڈ کورس — سرٹیفکیٹ تے کیریئر سپورٹ نال۔\n\nکسے وی کورس، فیس یا بیچ بارے پُچھو، یا تھلے توں درخواست دیو۔",
};

export function departmentGreeting(
  department: Department,
  language: Language
): { text: string; buttons: ReplyButton[] } {
  return {
    text: pick(department === "MARKETING" ? MARKETING_GREETING : INSTITUTE_GREETING, language),
    buttons: quickActions(department, language),
  };
}

// ----------------------------------------------------------- Quick actions --

const GET_QUOTE: Localised = {
  en: "💼 Get a quote",
  ur: "💼 قیمت معلوم کریں",
  ur_roman: "💼 Quote lein",
  pa: "💼 ریٹ پُچھو",
};

const APPLY: Localised = {
  en: "🎓 Apply now",
  ur: "🎓 داخلہ لیں",
  ur_roman: "🎓 Apply karein",
  pa: "🎓 داخلہ لوو",
};

const TALK_TO_TEAM: Localised = {
  en: "🙋 Talk to a human",
  ur: "🙋 نمائندے سے بات",
  ur_roman: "🙋 Team se baat",
  pa: "🙋 بندے نال گل",
};

const SWITCH: Localised = {
  en: "🔄 Other business",
  ur: "🔄 دوسرا ادارہ",
  ur_roman: "🔄 Doosra idara",
  pa: "🔄 دوجا ادارہ",
};

/** The two or three chips offered under an answer. */
export function quickActions(department: Department, language: Language): ReplyButton[] {
  return [
    department === "MARKETING"
      ? { id: `${ACTION_BUTTON_PREFIX}capture`, title: pick(GET_QUOTE, language) }
      : { id: `${ACTION_BUTTON_PREFIX}capture`, title: pick(APPLY, language) },
    { id: `${ACTION_BUTTON_PREFIX}human`, title: pick(TALK_TO_TEAM, language) },
    { id: `${ACTION_BUTTON_PREFIX}menu`, title: pick(SWITCH, language) },
  ];
}

// ------------------------------------------------------------ Transactional --

const LEAD_CONFIRMED: Localised = {
  en: "✅ *All done, {name}!*\n\nYour request is logged as *{reference}*.\n\nOur BITSOL Marketing team will call you on {phone} within one working day with a tailored proposal.\n\nAnything else I can help with meanwhile?",
  ur: "✅ *مکمل ہو گیا، {name}!*\n\nآپ کی درخواست *{reference}* کے نمبر پر درج ہو گئی ہے۔\n\nبِٹسول مارکیٹنگ کی ٹیم ایک کاروباری دن کے اندر {phone} پر رابطہ کرے گی۔\n\nاِس دوران کوئی اور مدد؟",
  ur_roman:
    "✅ *Ho gaya, {name}!*\n\nAap ki request *{reference}* ke number par register ho gayi hai.\n\nBITSOL Marketing ki team ek working day mein {phone} par call karegi.\n\nIs dauran koi aur madad?",
  pa: "✅ *ہو گیا، {name}!*\n\nتہاڈی درخواست *{reference}* نمبر تے لکھی گئی اے۔\n\nبِٹسول مارکیٹنگ دی ٹیم اک کم والے دن اندر {phone} تے کال کرے گی۔\n\nایس دوران ہور کوئی مدد؟",
};

const ADMISSION_CONFIRMED: Localised = {
  en: "✅ *Registered, {name}!*\n\nYour admission inquiry number is *{reference}*.\n\nAn admissions officer from BITSOL Institute will call you on {phone} to confirm the fee plan and the next batch.\n\nAnything else you'd like to know?",
  ur: "✅ *درج ہو گیا، {name}!*\n\nآپ کا داخلہ انکوائری نمبر *{reference}* ہے۔\n\nبِٹسول انسٹی ٹیوٹ کا داخلہ آفیسر {phone} پر کال کر کے فیس پلان اور اگلے بیچ کی تصدیق کرے گا۔\n\nکچھ اور جاننا چاہیں گے؟",
  ur_roman:
    "✅ *Register ho gaya, {name}!*\n\nAap ka admission inquiry number *{reference}* hai.\n\nBITSOL Institute ka admission officer {phone} par call kar ke fee plan aur next batch confirm karega.\n\nAur kuch jaanna chahenge?",
  pa: "✅ *لکھیا گیا، {name}!*\n\nتہاڈا داخلہ انکوائری نمبر *{reference}* اے۔\n\nبِٹسول انسٹی ٹیوٹ دا داخلہ افسر {phone} تے کال کر کے فیس پلان تے اگلا بیچ پکا کرے گا۔\n\nہور کجھ جاݨنا چاہوگے؟",
};

export function captureConfirmation(
  department: Department,
  language: Language,
  values: { name: string; reference: string; phone: string }
): string {
  const template = pick(
    department === "MARKETING" ? LEAD_CONFIRMED : ADMISSION_CONFIRMED,
    language
  );
  return template
    .replace("{name}", values.name.split(" ")[0])
    .replace("{reference}", values.reference)
    .replace("{phone}", values.phone);
}

const CAPTURE_CANCELLED: Localised = {
  en: "No problem — I've cancelled that. Ask me anything, or reply *menu* to start over.",
  ur: "کوئی بات نہیں — میں نے منسوخ کر دیا۔ کچھ بھی پوچھیں، یا دوبارہ شروع کرنے کے لیے *menu* لکھیں۔",
  ur_roman:
    "Koi baat nahi — maine cancel kar diya. Kuch bhi poochein, ya dobara shuru karne ke liye *menu* likhein.",
  pa: "کوئی گل نئیں — میں رد کر دِتا۔ کجھ وی پُچھو، یا مُڑ شروع کرن لئی *menu* لکھو۔",
};

export const captureCancelled = (language: Language) => pick(CAPTURE_CANCELLED, language);

const ESCALATED: Localised = {
  en: "🎫 I've passed this to our team — your ticket is *{reference}*.\n\nSomeone will reply here shortly. You can also call {phone} during {hours}.",
  ur: "🎫 میں نے یہ ہماری ٹیم کو بھیج دیا ہے — آپ کا ٹکٹ *{reference}* ہے۔\n\nکوئی جلد یہیں جواب دے گا۔ آپ {hours} کے دوران {phone} پر کال بھی کر سکتے ہیں۔",
  ur_roman:
    "🎫 Maine ye hamari team ko bhej diya hai — aap ka ticket *{reference}* hai.\n\nKoi jald yahin reply karega. Aap {hours} mein {phone} par call bhi kar sakte hain.",
  pa: "🎫 میں ایہہ ساڈی ٹیم نوں بھیج دِتا اے — تہاڈا ٹکٹ *{reference}* اے۔\n\nکوئی چھیتی ایتھے ای جواب دیوے گا۔ تسی {hours} وچ {phone} تے کال وی کر سکدے او۔",
};

export function escalationNotice(
  department: Department,
  language: Language,
  reference: string
): string {
  const brand = BRANDS[department];
  return pick(ESCALATED, language)
    .replace("{reference}", reference)
    .replace("{phone}", brand.contact.phone)
    .replace("{hours}", brand.contact.hours);
}

const MEDIA_ACK: Localised = {
  en: "📎 Thanks — I've received that and attached it to your conversation. I can't open files myself, so please also describe what you need in a message.",
  ur: "📎 شکریہ — مجھے موصول ہو گیا اور آپ کی گفتگو سے منسلک کر دیا ہے۔ میں فائل خود نہیں کھول سکتا، اس لیے براہِ کرم پیغام میں بھی بتا دیں کہ آپ کو کیا چاہیے۔",
  ur_roman:
    "📎 Shukriya — mujhe mil gaya aur aap ki conversation se attach kar diya hai. Main file khud nahi khol sakta, is liye message mein bhi bata dein aap ko kya chahiye.",
  pa: "📎 شکریہ — مینوں مل گیا تے تہاڈی گل بات نال لا دِتا اے۔ میں فائل آپ نئیں کھول سکدا، ایس لئی سنیہے وچ وی دس دیو تہانوں کیہ چاہیدا اے۔",
};

export const mediaAcknowledgement = (language: Language) => pick(MEDIA_ACK, language);

const OPTED_OUT: Localised = {
  en: "You're unsubscribed from BITSOL broadcasts. 👍\n\nYou can still message here any time — send *start* to talk to the assistant again.",
  ur: "آپ بِٹسول کے پیغامات سے ان سبسکرائب ہو گئے ہیں۔ 👍\n\nآپ یہاں کبھی بھی پیغام بھیج سکتے ہیں — دوبارہ بات کرنے کے لیے *start* لکھیں۔",
  ur_roman:
    "Aap BITSOL broadcasts se unsubscribe ho gaye hain. 👍\n\nAap yahan kabhi bhi message kar sakte hain — dobara baat karne ke liye *start* likhein.",
  pa: "تسی بِٹسول دے پیغاماں توں ان سبسکرائب ہو گئے او۔ 👍\n\nتسی ایتھے کدے وی سنیہا بھیج سکدے او — مُڑ گل کرن لئی *start* لکھو۔",
};

export const optOutConfirmation = (language: Language) => pick(OPTED_OUT, language);

const BUSY: Localised = {
  en: "Sorry, I'm having trouble replying right now. Please try again in a moment, or call us on {phone}.",
  ur: "معذرت، ابھی جواب دینے میں دشواری ہو رہی ہے۔ تھوڑی دیر بعد کوشش کریں، یا {phone} پر کال کریں۔",
  ur_roman:
    "Maazrat, abhi reply karne mein dikkat ho rahi hai. Thori der baad koshish karein, ya {phone} par call karein.",
  pa: "معافی، ہُݨے جواب دیݨ وچ اوکھ آ رہی اے۔ تھوڑی دیر بعد کوشش کرو، یا {phone} تے کال کرو۔",
};

export function busyNotice(department: Department | null, language: Language): string {
  const phone = (department ? BRANDS[department] : BRANDS.MARKETING).contact.phone;
  return pick(BUSY, language).replace("{phone}", phone);
}
